export const items = [
  {
    id: 1,
    title: "Гироскутер Smart Balance Well 6.5 Хип-Хоп (АКВАЗАЩИТА)",
    type: "Сигвеи",
    price: 5400,
    lastPrice: 4900,
    discount: 10,
    rate: 5,
    favorite: true,
    waterProof: true,
    new: true,
    hit: true,
    img: "https://i.postimg.cc/PqZtk5x7/image-18.png",
  },
  {
    id: 2,
    title: "Гироскутер Smart Balance Premium 10.5 Зелёный граффити",
    type: "Сигвеи",
    price: 5400,
    lastPrice: 4900,
    discount: 10,
    rate: 4,
    favorite: true,
    waterProof: true,
    new: false,
    hit: true,
    img: "https://i.postimg.cc/PqZtk5x7/image-18.png",
  },
  {
    id: 3,
    title: "Гироскутер Smart Balance",
    type: "Сигвеи",
    price: 15000,
    lastPrice: 13500,
    discount: 10,
    rate: 5,
    favorite: false,
    waterProof: true,
    new: false,
    hit: false,
    img: "https://i.postimg.cc/PqZtk5x7/image-18.png",
  },
  {
    id: 4,
    title: "Гироскутер Smart Balance Well 6.5 (АКВАЗАЩИТА)",
    type: "Сигвеи",
    price: 5400,
    lastPrice: 4900,
    discount: 10,
    rate: 3,
    favorite: true,
    waterProof: true,
    new: true,
    hit: false,
    img: "https://i.postimg.cc/PqZtk5x7/image-18.png",
  },
];
