export const store = {
  items: [
    {
      id: 0,
      title: "SE RR",
      rate: 5,
      made: "Китай",
      type: "Электромотоцикл",
      lastPrice: 480000,
      discount: false,
      img: "https://i.postimg.cc/hjwYQW8j/serr01.jpg",
      maxSpeed: "120 км/ч",
      powerReserve: "110 км",
    },
    {
      id: 1,
      title: "DWX 250",
      rate: 5,
      made: "Россия",
      type: "Электромотоцикл",
      lastPrice: 960000,
      discount: false,
      img: "https://i.postimg.cc/Z5h1LSGv/250dwx01.jpg",
      maxSpeed: "120 км/ч",
      powerReserve: "120 км",
    },
    {
      id: 2,
      title: "SE R3",
      rate: 5,
      made: "Китай",
      type: "Электромотоцикл",
      price: 480000,
      lastPrice: 561600,
      discount: true,
      img: "https://i.postimg.cc/gcxFz4yj/r3se01.jpg",
      maxSpeed: "120 км/ч",
      powerReserve: "110 км",
    },
    {
      id: 3,
      title: "Zero SR/F Premium",
      rate: 5,
      made: "США",
      type: "Электромотоцикл",
      lastPrice: 3493800,
      discount: false,
      img: "https://i.postimg.cc/Y0Gx5vW2/srf01.jpg",
      maxSpeed: "200 км/ч",
      powerReserve: "419 км",
    },
    {
      id: 4,
      title: "SE Tundra",
      rate: 5,
      made: "Китай",
      type: "Электроквадроцикл",
      lastPrice: 1220400,
      discount: false,
      img: "https://i.postimg.cc/0QNnCW5w/set01.jpg",
      maxSpeed: "95 км/ч",
      powerReserve: "60-90 км",
    },
    {
      id: 5,
      title: "SE Hummer",
      rate: 5,
      made: "Китай",
      type: "Электроквадроцикл",
      lastPrice: 800000,
      discount: false,
      img: "https://i.postimg.cc/vmhXfFyy/seh01.jpg",
      maxSpeed: "60 км/ч",
      powerReserve: "80 км",
    },
    {
      id: 6,
      title: "Linhai LH40DA",
      rate: 5,
      made: "Китай",
      type: "Электроквадроцикл",
      lastPrice: 680000,
      discount: false,
      img: "https://i.postimg.cc/KcHq02Mv/40lnh01.jpg",
      maxSpeed: "60 км/ч",
      powerReserve: "80 км",
    },
    {
      id: 7,
      title: "ELIQ (Кит Комплект для электрификации BRP)",
      rate: 5,
      made: "Россия",
      type: "Электроквадроцикл",
      lastPrice: 680000,
      discount: false,
      img: "https://i.postimg.cc/BbXhJhd0/eliqbrp02.jpg",
      maxSpeed: "90 км/ч",
      powerReserve: "90 км",
    },
    {
      id: 8,
      title: "ELIQ Арктик",
      rate: 5,
      made: "Россия",
      type: "Электроснегоход",
      lastPrice: 490100,
      discount: false,
      img: "https://i.postimg.cc/s24HmGpt/eliqarc01.jpg",
      maxSpeed: "45 км/ч",
      powerReserve: "0 км",
    },
    {
      id: 9,
      title: "SE Alaska",
      rate: 5,
      made: "Россия",
      type: "Электроснегоход",
      lastPrice: 1250000,
      discount: false,
      img: "https://i.postimg.cc/JhLdj5BN/sealaska01.jpg",
      maxSpeed: "75 км/ч",
      powerReserve: "60 км",
    },
    {
      id: 10,
      title: "ELIQ",
      rate: 5,
      made: "Россия",
      type: "Электросноуборд",
      lastPrice: 409000,
      discount: false,
      img: "https://i.postimg.cc/CMPt98W0/eliqboard01.jpg",
      maxSpeed: "65 км/ч",
      powerReserve: "30 км",
    },
    {
      id: 11,
      title: "Tesla Model 3 I 2021 г.",
      rate: 5,
      made: "США",
      type: " Электромобиль",
      lastPrice: 6129800,
      discount: false,
      img: "https://i.postimg.cc/SKFHDpHz/3tesla01.jpg",
    },
    {
      id: 12,
      title: "NIO ES8",
      rate: 5,
      made: "Китай",
      type: "Электромобиль",
      lastPrice: 9402400,
      discount: false,
      img: "https://i.postimg.cc/J0nFG7HS/es8nio01.jpg",
      maxSpeed: "200 км/ч",
      powerReserve: "580 км",
    },
    {
      id: 13,
      title: "NIO ET7",
      rate: 5,
      made: "Китай",
      type: "Электромобиль",
      lastPrice: 8415400,
      discount: false,
      img: "https://i.postimg.cc/zXQsHhj7/et7nio01.jpg",
      maxSpeed: "200 км/ч",
      powerReserve: "700 км",
    },
    {
      id: 14,
      title: "X-PENG P7 WING 4WD (ВЕРСИЯ PENGYI)",
      rate: 5,
      type: "Электромобиль",
      lastPrice: 6373900,
      discount: false,
      img: "https://i.postimg.cc/Zn71cvhT/p7xpeng01.jpg",
      maxSpeed: "170 км/ч",
      powerReserve: "706 км",
    },
    {
      id: 15,
      title: "NVX",
      rate: 5,
      made: "Китай",
      type: "Электроскутер",
      price: 450000,
      lastPrice: 294580,
      discount: true,
      img: "https://i.postimg.cc/0N71sN7f/nvx01.jpg",
      maxSpeed: "110 км/ч",
      powerReserve: "100 км",
    },
    {
      id: 16,
      title: "Внедорожный Электробайк ELIQ",
      rate: 5,
      made: "Россия",
      type: "Электроскутер",
      lastPrice: 260000,
      discount: false,
      img: "https://i.postimg.cc/gk0pZmPz/eliqbike01.jpg",
      maxSpeed: "110 км/ч",
      powerReserve: "100 км",
    },
    {
      id: 17,
      title: "Максискутер D1",
      rate: 5,
      made: "Китай",
      type: "Электроскутер",
      lastPrice: 462400,
      discount: false,
      img: "https://i.postimg.cc/BZpsbtk7/d101.jpg",
      maxSpeed: "100 км/ч",
      powerReserve: "100 км",
    },
    {
      id: 18,
      title: "Электротрицикл D1 5000",
      rate: 5,
      type: "Электроскутер",
      lastPrice: 670000,
      discount: false,
      img: "https://i.postimg.cc/0yb9LxtW/5000d101.jpg",
      maxSpeed: "100 км/ч",
      powerReserve: "100 км",
    },
    {
      id: 19,
      title: "INTRO Bump (черный)",
      rate: 5,
      type: "Электровелосипед",
      lastPrice: 49900,
      discount: false,
      img: "https://i.postimg.cc/yxsV5Z5c/introbump01.jpg",
      maxSpeed: "25 км/ч",
      powerReserve: "70 км",
    },
    {
      id: 20,
      title: "e-Alfa New",
      rate: 5,
      type: "Электровелосипед",
      lastPrice: 54300,
      discount: false,
      img: "https://i.postimg.cc/Lsg6ZRLY/newealfa01.jpg",
      powerReserve: "50 км",
    },
    {
      id: 21,
      title: "e-Alfa GL",
      rate: 5,
      type: "Электровелосипед",
      lastPrice: 70900,
      discount: false,
      img: "https://i.postimg.cc/MZ7HDW41/glealfa01.jpg",
      powerReserve: "50 км",
    },
    {
      id: 22,
      title: "Porter FAT 500",
      rate: 5,
      type: "Электровелосипед",
      lastPrice: 117200,
      discount: false,
      img: "https://i.postimg.cc/wMQBTVJw/fat500porter01.jpg",
      powerReserve: "40 км",
    },
    {
      id: 23,
      title: "Электрический багги MC-146",
      rate: 5,
      type: "Для детей",
      lastPrice: 499000,
      discount: false,
      img: "https://i.postimg.cc/htyfdpYw/mc14601.jpg",
      powerReserve: "50 км",
      maxSpeed: "40 км/ч",
      made: "Китай",
    },
    {
      id: 24,
      title: "Электрический автомобиль D Car-1000 (Мини-Caterham)",
      rate: 5,
      type: "Для детей",
      lastPrice: 2908000,
      discount: false,
      img: "https://i.postimg.cc/QxD9GB56/dcar100001.jpg",
      powerReserve: "80 км",
      maxSpeed: "45 км/ч",
    },
  ],
};
